source "https://rubygems.org"
gem "sinatra"
gem "json"
gem "i18n"
gem "active_support"
gem "pry"
gem "mongo"
gem "rack"
gem "rack-test", :require => "rack/test"
gem "rspec", :require => "rspec/autorun"
gem "shotgun"
gem "haml"
